### ISSUE TITLE
portfolio.mdをREADME.mdに変える提案

### ISSUE THREAD

**Issue by Kasugaccho** [shoko218/portfolio#1]
当リポジトリは1ファイル(portfolio.md)のみで構成されており、README.mdがないためリポジトリを開いた際に何も文章が表示されません。

そこで、「portfolio.md」を「README.md」に名前変更することを提案します。

**Comment by shoko218** [comment]
ご返答が遅くなってしまい、すみません。
恥ずかしながらこちらのIssueに先ほど気がつきました。
ご指摘ありがとうございます！
ご提案の通りにさせていただきました。
